skip_commits:
  message: /updated readme/       # Regex for matching commit message

install:
  - cinst pester

build: false

test_script:
  - ps: Write-Output "Testing with PowerShell $($PSVersionTable.PSVersion)"
  - ps: $PesterOutput = Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile TestsResults.xml -PassThru
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults.xml))
  - ps: if ($PesterOutput.FailedCount -gt 0) { throw "$($PesterOutput.FailedCount) tests failed."}
  - ps: Write-Output "Testing with PowerShell 2 $($PSVersionTable.PSVersion)"
  - PowerShell.exe -NoProfile -ExecutionPolicy Bypass -Version 2.0 -Command "$PesterOutput2 = Invoke-Pester -Path '.\Tests' -OutputFormat NUnitXml -OutputFile TestsResults2.xml -PassThru"
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestsResults2.xml))
  - ps: if ($PesterOutput2.FailedCount -gt 0) { throw "$($PesterOutput2.FailedCount) tests failed for PowerShell v2."}